name: FakePlayers
main: de.Herbystar.FakePlayers.Main
version: 1.21
author: Herbystar
description: A plugin to manipulate the online count!
commands:
  fakePlayers:
    usage: /fakePlayers
    description: main command.
    permission: FakePlayers.Commands
  help:
    usage: /help
    description: Displays help information for FakePlayers plugin
    permission: FakePlayers.Commands
permissions:
  FakePlayers.Commands:
    description: Permission for all ingame commands!
